GET  http://localhost:3000/auth
Content-Type: application/json

{
    "username":"newname",
    "email":"newname@name.com",
    "password":"newname"
}

###
GET  http://localhost:3000/auth/login
Content-Type: application/json

{
    "username":"newname",
    "email":"newname@name.com",
    "password":"newname"
}


###
GET  http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI3M2FjZjU0YTQ3MjgyMGVkMzM2NjciLCJ1c2VybmFtZSI6Im5ld25hbWUxIiwiZW1haWwiOiJuZXduYW1lQG5hbWUxLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDV0eEhjVTVDWUdkdUdubDlNVFlLUnVvLldGRjViTGtGR2tpeU5qUWdISVp1OHRVcmFwNHZhIiwidG9kb3MiOltdLCJfX3YiOjAsImlhdCI6MTY4MDQzMDQxOCwiZXhwIjoxNjgwNDM3NjE4fQ.bl8WuZ4a1_ZDQkQ5vvDBwajK2Yr1He_HSqRmPJxFPp8

###
PATCH http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI3M2FjZjU0YTQ3MjgyMGVkMzM2NjciLCJ1c2VybmFtZSI6Im5ld25hbWUxIiwiZW1haWwiOiJuZXduYW1lQG5hbWUxLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDV0eEhjVTVDWUdkdUdubDlNVFlLUnVvLldGRjViTGtGR2tpeU5qUWdISVp1OHRVcmFwNHZhIiwidG9kb3MiOltdLCJfX3YiOjAsImlhdCI6MTY4MDQzMDQxOCwiZXhwIjoxNjgwNDM3NjE4fQ.bl8WuZ4a1_ZDQkQ5vvDBwajK2Yr1He_HSqRmPJxFPp8



###
GET  http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI3MGRkNWVlMTdiYmQ2NWIzODhhMmEiLCJ1c2VybmFtZSI6Im5ld25hbWUiLCJlbWFpbCI6Im5ld25hbWVAbmFtZS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRRMU9lTS4vSDkxSHhwMmNNVWtCckxPeWh3Q3Y1djVWRnRZVkY4SmJCNGdmME52NklNZFBSVyIsInRvZG9zIjpbXSwiX192IjowLCJpYXQiOjE2ODA0MzA2MjMsImV4cCI6MTY4MDQzNzgyM30.4eSUlCX_55MXD4OSNYbAHSe2yqvmIAvWmluNnxdrGWc



###
GET  http://localhost:3000/6428a37de0d7b9150a6e28e2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI3MGRkNWVlMTdiYmQ2NWIzODhhMmEiLCJ1c2VybmFtZSI6Im5ld25hbWUiLCJlbWFpbCI6Im5ld25hbWVAbmFtZS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRRMU9lTS4vSDkxSHhwMmNNVWtCckxPeWh3Q3Y1djVWRnRZVkY4SmJCNGdmME52NklNZFBSVyIsInRvZG9zIjpbXSwiX192IjowLCJpYXQiOjE2ODA0MzA2MjMsImV4cCI6MTY4MDQzNzgyM30.4eSUlCX_55MXD4OSNYbAHSe2yqvmIAvWmluNnxdrGWc




###
PATCH  http://localhost:3000/6428a37de0d7b9150a6e28e2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI3M2FjZjU0YTQ3MjgyMGVkMzM2NjciLCJ1c2VybmFtZSI6Im5ld25hbWUxIiwiZW1haWwiOiJuZXduYW1lQG5hbWUxLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDV0eEhjVTVDWUdkdUdubDlNVFlLUnVvLldGRjViTGtGR2tpeU5qUWdISVp1OHRVcmFwNHZhIiwidG9kb3MiOltdLCJfX3YiOjAsImlhdCI6MTY4MDQzMDQxOCwiZXhwIjoxNjgwNDM3NjE4fQ.bl8WuZ4a1_ZDQkQ5vvDBwajK2Yr1He_HSqRmPJxFPp8
Content-Type: application/json

{
    "title":"my forth todo",
    "description":"this is description for my forth todo"
}






###
POST  http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI3M2FjZjU0YTQ3MjgyMGVkMzM2NjciLCJ1c2VybmFtZSI6Im5ld25hbWUxIiwiZW1haWwiOiJuZXduYW1lQG5hbWUxLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDV0eEhjVTVDWUdkdUdubDlNVFlLUnVvLldGRjViTGtGR2tpeU5qUWdISVp1OHRVcmFwNHZhIiwidG9kb3MiOltdLCJfX3YiOjAsImlhdCI6MTY4MDQzMDQxOCwiZXhwIjoxNjgwNDM3NjE4fQ.bl8WuZ4a1_ZDQkQ5vvDBwajK2Yr1He_HSqRmPJxFPp8
Content-Type: application/json

{
    "title":"my forth todo",
    "description":"this is description for my forth todo"
}




###
POST  http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI3MGRkNWVlMTdiYmQ2NWIzODhhMmEiLCJ1c2VybmFtZSI6Im5ld25hbWUiLCJlbWFpbCI6Im5ld25hbWVAbmFtZS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRRMU9lTS4vSDkxSHhwMmNNVWtCckxPeWh3Q3Y1djVWRnRZVkY4SmJCNGdmME52NklNZFBSVyIsInRvZG9zIjpbXSwiX192IjowLCJpYXQiOjE2ODA0MzA2MjMsImV4cCI6MTY4MDQzNzgyM30.4eSUlCX_55MXD4OSNYbAHSe2yqvmIAvWmluNnxdrGWc
Content-Type: application/json


{
    "title":"this is my first todo",
    "description":"this is description for my first todo"
}
